x-service-template: &frontend-service
  networks:
    - luis
  restart: always

services:
  desarrollo-services:    
    <<: *frontend-service
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    

networks:
  luis:
    external: true