x-service-template: &frontend-service
  build:
    context: .
    dockerfile: Dockerfile

services:
  sysintegra-services:
    <<: *frontend-service
    image: sysintegra-frontend
    
  leatsac-services:
    <<: *frontend-service
    image: leatsac-frontend

  ferreteria-rym-services:
    <<: *frontend-service
    image: ferreteria-rym-frontend

  importmuneli-services:
    <<: *frontend-service
    image: importmuneli-frontend

  # supermarketya-services:
  #   <<: *frontend-service
  #   image: supermarketya-frontend

  dracoly-services:
    <<: *frontend-service
    image: dracoly-frontend

  # masa-y-miga-services:
  #   <<: *backend-service
  #   image: masa-y-miga-backend

  # main-services:
  #   <<: *backend-service
  #   image: main-backend
