x-service-template: &frontend-service
  build:
    context: .
    dockerfile: Dockerfile

services:
  leatsac-services:
    <<: *frontend-service
    image: leatsac-frontend

  ferreteria-rym-services:
    <<: *frontend-service
    image: ferreteria-rym-frontend

  importmuneli-services:
    <<: *frontend-service
    image: importmuneli-frontend

  supermarketya-services:
    <<: *frontend-service
    image: supermarketya-frontend

  dracoly-services:
    <<: *frontend-service
    image: dracoly-frontend

  main-services:
    <<: *frontend-service
    image: main-frontend

  desarrollo-services:
    <<: *frontend-service
    image: desarrollo-frontend
