version: '3'

# Definición de un servicio base reutilizable
x-service-template: &frontend-service
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - luis
  restart: always
  deploy:
    resources:
      limits:
        cpus: "0.5"   # Máximo 50% de un núcleo
        memory: "512m" # Máximo 512MB de RAM
      reservations:
        cpus: "0.25"   # Reserva 25% de un núcleo
        memory: "256m" # Reserva 256MB de RAM

services:
  sysintegra-services:
    <<: *frontend-service
    image: sysintegra-frontend-image
    container_name: sysintegra-frontend
    ports:
      - 6000:80

  importmuneli-services:
    <<: *frontend-service
    image: importmuneli-frontend-image
    container_name: importmuneli-frontend
    ports:
      - 6010:80

  raices-services:
    <<: *frontend-service
    image: raices-frontend-image
    container_name: raices-frontend
    ports:
      - 6014:80

  felicitygirls-tiquepos-services:
    <<: *frontend-service
    image: felicitygirls-tiquepos-frontend-image
    container_name: felicitygirls-tiquepos-frontend
    ports:
      - 6018:80

  bodega-modelo-services:
    <<: *frontend-service
    image: bodega-modelo-frontend-image
    container_name: bodega-modelo-frontend
    ports:
      - 6022:80

  unnagro-services:
    <<: *frontend-service
    image: unnagro-frontend-image
    container_name: unnagro-frontend
    ports:
      - 6026:80

  leatsac-services:
    <<: *frontend-service
    image: leatsac-frontend-image
    container_name: leatsac-frontend
    ports:
      - 6030:80

  ferreteria-rym-services:
    <<: *frontend-service
    image: ferreteria-rym-frontend-image
    container_name: ferreteria-rym-frontend
    ports:
      - 6034:80

  asiaticos-pcl-services:
    <<: *frontend-service
    image: asiaticos-pcl-frontend-image
    container_name: asiaticos-pcl-frontend
    ports:
      - 6036:80

  supermarketya-services:
    <<: *frontend-service
    image: supermarketya-frontend-image
    container_name: supermarketya-frontend
    ports:
      - 6038:80

  dracoly-services:
    <<: *frontend-service
    image: dracoly-frontend-image
    container_name: dracoly-frontend
    # ports:
      # - 6038:80

  main-services:
    <<: *frontend-service
    image: main-frontend-image
    container_name: main-frontend
    # ports:
      # - 6038:80

networks:
  luis:
    external: true
