
export const TIPO_PEDIDO_ENVIO_DOMICILIO = 'TP0001';
export const TIPO_PEDIDO_RECOJO_LOCAL = 'TP0002';
export const TIPO_PEDIDO_ENTREGA_PROGRAMADA = 'TP0003';
export const TIPO_PEDIDO_ENVIO_POR_AGENCIA = 'TP0004';