name: Docker Image CI - SysSoftIntegra FrontEnd Production

on:
  push:
    branches: 
      - "master"

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: leatsac
            service: leatsac-services
          - environment: ferreteria-rym
            service: ferreteria-rym-services
          - environment: importmuneli
            service: importmuneli-services
          # - environment: supermarketya
          #   service: supermarketya-services
          - environment: dracoly
            service: dracoly-services
          # - environment: main
          #   service: main-services
  
    environment: ${{ matrix.environment }}

    env:
      ECR_IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/syssoftintegra/front-end-production:${{ matrix.environment }}-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat > .env <<EOL
          VITE_APP_BACK_END="${{secrets.VITE_APP_BACK_END}}"
          VITE_APP_APIS_PERU="${{secrets.VITE_APP_APIS_PERU}}"
          VITE_APP_ENV="${{vars.VITE_APP_ENV}}"
          VITE_APP_NAME="${{vars.VITE_APP_NAME}}"
          EOL

      - name: Build Docker image
        run: docker compose -f docker-compose.build.yml build ${{ matrix.service }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1 
      
      - name: Tag front-end image
        run: docker tag ${{ matrix.environment }}-frontend $ECR_IMAGE_URI

      - name: Push front-end image to ECR
        run: docker push $ECR_IMAGE_URI

  deploy-to-runs-on:
    name: Deploy to Production Server
    runs-on: [self-hosted, client-dbsmart]
    needs: build-and-push

    strategy:
      matrix:
        include:
          - environment: leatsac
            service: leatsac-services
          - environment: ferreteria-rym
            service: ferreteria-rym-services
          - environment: importmuneli
            service: importmuneli-services
          # - environment: supermarketya
          #   service: supermarketya-services
          - environment: dracoly
            service: dracoly-services
          # - environment: main
          #   service: main-services

    env:
      CONTAINER_NAME: ${{ matrix.environment }}-frontend
      IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/syssoftintegra/front-end-production:${{ matrix.environment }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download image from Amazon ECR
        run: docker pull $IMAGE_NAME

      - name: Create and run container
        run: docker compose -f docker-compose.prod.yml up ${{ matrix.service }} -d

      - name: Clean up local Docker images
        run: docker builder prune --all || true
  
  clean-ecr-images:
    name: Clear up old images in ECR
    runs-on: ubuntu-latest
    needs: deploy-to-runs-on

    strategy:
      matrix:
        include:
          - environment: leatsac
          - environment: ferreteria-rym
          - environment: importmuneli
          # - environment: supermarketya
          - environment: dracoly
          # - environment: main
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Delete old images from ECR
        run: |
          REPO="syssoftintegra/front-end-production"
          ENV="${{ matrix.environment }}"
          TAG="${ENV}-latest"

          aws ecr list-images \
          --repository-name "$REPO" \
          --query "imageIds[?type(imageTag)==null || imageTag!='${TAG}']" \
          --output json > images.json

          COUNT=$(jq length images.json)

          if [ "$COUNT" -gt 0 ]; then
            echo "🗑️ Cleaning up $COUNT old images from $REPO..."
            
            aws ecr batch-delete-image \
              --repository-name "$REPO" \
              --image-ids file://images.json
          else
            echo "✅ There are no old images to delete from $REPO."
          fi
