name: Docker Staging CI - SysSoftIntegra FrontEnd

# Definición de eventos desencadenadores
on:
  push:
    branches: 
      - test

# Definición de trabajos
jobs:
  build-and-deploy-app-test:
    runs-on: self-hosted
    environment: desarrollo

    env:  
      VITE_APP_BACK_END: ${{ secrets.VITE_APP_BACK_END }}
      VITE_APP_APIS_PERU: ${{ secrets.VITE_APP_APIS_PERU }}
      VITE_APP_ENV: ${{ vars.VITE_APP_ENV }}
      VITE_APP_VERSION: ${{ vars.VITE_APP_VERSION }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          VITE_APP_BACK_END="${{env.VITE_APP_BACK_END}}"
          VITE_APP_APIS_PERU="${{env.VITE_APP_APIS_PERU}}"
          VITE_APP_ENV="${{env.VITE_APP_ENV}}"
          VITE_APP_VERSION="${{env.VITE_APP_VERSION}}"
          EOL

      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build sysintegra-services -d