name: Docker Staging CI - SysSoftIntegra FrontEnd

# Definición de eventos desencadenadores
on:
  push:
    branches: 
      - staging

# Definición de trabajos
jobs:
  build-and-deploy-app-legrand-tiquepos:
    runs-on: self-hosted
    environment: legrand-tiquepos
      
    env:  
      VITE_APP_BACK_END: ${{ secrets.VITE_APP_BACK_END }}
      VITE_APP_CPE_SUNAT: ${{ secrets.VITE_APP_CPE_SUNAT }}
      VITE_APP_APIS_PERU: ${{ secrets.VITE_APP_APIS_PERU }}
      VITE_APP_IMAGE: ${{ secrets.VITE_APP_IMAGE }}
      VITE_APP_PDF: ${{ secrets.VITE_APP_PDF }}
      
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          VITE_APP_BACK_END="${{env.VITE_APP_BACK_END}}"
          VITE_APP_CPE_SUNAT="${{env.VITE_APP_CPE_SUNAT}}"
          VITE_APP_APIS_PERU="${{env.VITE_APP_APIS_PERU}}"
          VITE_APP_IMAGE="${{env.VITE_APP_IMAGE}}"
          VITE_APP_PDF="${{env.VITE_APP_PDF}}"
          EOL
      
      - name: Creando y ejecutando contenedor
        run: docker compose up --build legrand-tiquepos-services -d